api_key: sk-proj-xxx-xxx-xxx

system_prompt: >
  You are a skilled technical blog writer. Write clear, informative, and engaging content with a consistent tone and style.

temperature: 0.7

content_prompt_template: >
  Write a blog post titled '{title}' based on this synopsis:
  {synopsis}

default_model: gpt-4o
default_max_tokens: 1500
tokens_per_minute: 225  # Token estimate for reading time
